export const styles: { [key: string]: React.CSSProperties } = {
  homePageContainer: {
    padding: "20px",
    backgroundColor: "#232324",
    maxWidth: "1800px",
    marginLeft: "50px",
    borderRadius: "15px",
    marginTop: "40px",
  },
  menuCards: {
    display: "flex",
    justifyContent: "space-evenly",
    margin: "auto",
  },
  cards: {
    width: "200px",
    margin: "auto",
    marginBottom: "50px",
    alignItems: "center",
    paddingTop: "12px",
  },
  gridDisplay: {
    display: "flex",
    justifyContent: "space-around",
    flexWrap: "wrap",
  },
  gridContainer: {
    marginTop: "30px",
    display: "flex",
    justifyContent: "space-evenly",
    flexWrap: "wrap",
    padding: "20px",
    backgroundColor: "#232324",
    maxWidth: "1400px",
    marginLeft: "20px",
    borderRadius: "15px",
  },
  menuGridContainer: {
    marginTop: "30px",
    display: "flex",
    justifyContent: "space-evenly",
    flexWrap: "wrap",
    padding: "20px",
    backgroundColor: "#232324",
    maxWidth: "1400px",
    marginLeft: "200px",
    borderRadius: "15px",
  },
  customIntroBar: {
    marginTop: "30px",
    display: "flex",
    justifyContent: "space-evenly",
    flexWrap: "wrap",
    padding: "20px",
    backgroundColor: "#232324",
    maxWidth: "1400px",
    marginLeft: "15px",
    borderRadius: "15px",
  },
  customCrustContainer: {
    marginTop: "30px",
    padding: "20px",
    backgroundColor: "#232324",
    maxWidth: "1400px",
    marginLeft: "20px",
    borderRadius: "15px",
    display: "flex",
  },
  title: {
    color: "white",
    display: "flex",
    justifyContent: "space-evenly",
    marginTop: "20px",
    textAlign: "center",
  },
  blackTitle: {
    color: "black",
    display: "flex",
    justifyContent: "space-evenly",
  },
  greenButton: {
    backgroundColor: "#325B4F",
    border: "hidden",
  },
  menuImageSizes: {
    maxWidth: "16rem",
    maxHeight: "16rem",
    paddingBottom: "12px",
  },
  customTotalContainer: {
    padding: "2px",
    backgroundColor: "#232324",
    maxWidth: "400px",
    marginRight: "80px",
    borderRadius: "15px",
    position: "fixed",
    bottom: "250px",
    right: "0",
    width: "375px",
  },
  totalPie: {
    color: "white",
  },
  cartCheckoutContainer: {
    marginTop: "30px",
    display: "flex",
    justifyContent: "space-evenly",
    flexWrap: "wrap",
    padding: "20px",
    backgroundColor: "#232324",
    maxWidth: "1400px",
    marginLeft: "225px",
    borderRadius: "15px",
  },
};

export default styles;
